[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding="50"

Font="JetBrainsMono Nerd Font"
FontSize="13"

KeyboardSize="0.4"

RoundCorners="12"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

HeaderText="Tokyo Night"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/tokyonight.png"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.3"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

HeaderTextColor="#7aa2f7"
DateTextColor="#c0caf5"
TimeTextColor="#c0caf5"

FormBackgroundColor="#1a1b26"
BackgroundColor="#1a1b26"
DimBackgroundColor="#1a1b26"

LoginFieldBackgroundColor="#24283b"
PasswordFieldBackgroundColor="#24283b"
LoginFieldTextColor="#c0caf5"
PasswordFieldTextColor="#c0caf5"
UserIconColor="#7aa2f7"
PasswordIconColor="#bb9af7"

PlaceholderTextColor="#565f89"
WarningColor="#f7768e"

LoginButtonTextColor="#1a1b26"
LoginButtonBackgroundColor="#7aa2f7"
SystemButtonsIconsColor="#c0caf5"
SessionButtonTextColor="#c0caf5"
VirtualKeyboardButtonTextColor="#c0caf5"

DropdownTextColor="#c0caf5"
DropdownSelectedBackgroundColor="#3b4261"
DropdownBackgroundColor="#24283b"

HighlightTextColor="#c0caf5"
HighlightBackgroundColor="#3b4261"
HighlightBorderColor="#7aa2f7"

HoverUserIconColor="#7dcfff"
HoverPasswordIconColor="#7dcfff"
HoverSystemButtonsIconsColor="#7dcfff"
HoverSessionButtonTextColor="#7dcfff"
HoverVirtualKeyboardButtonTextColor="#7dcfff"

#################### Form ####################

PartialBlur="true"
FullBlur="false"
BlurMax="32"
Blur="1.0"

HaveFormBackground="true"
FormPosition="center"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

#################### Translation ####################

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
