[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding="0"

Font="JetBrainsMono Nerd Font"
FontSize="12"

KeyboardSize="0.4"

RoundCorners="0"

Locale=""
HourFormat="HH:mm"
DateFormat="M/dd"

HeaderText="ACCESS GRANTED"

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/tokyonight.png"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.4"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

HeaderTextColor="#f7768e"
DateTextColor="#ff9e64"
TimeTextColor="#7dcfff"

FormBackgroundColor="#1a1b26"
BackgroundColor="#1a1b26"
DimBackgroundColor="#1a1b26"

LoginFieldBackgroundColor="#f7768e"
PasswordFieldBackgroundColor="#f7768e"
LoginFieldTextColor="#7dcfff"
PasswordFieldTextColor="#7dcfff"
UserIconColor="#7dcfff"
PasswordIconColor="#7dcfff"

PlaceholderTextColor="#bb9af7"
WarningColor="#f7768e"

LoginButtonTextColor="#7dcfff"
LoginButtonBackgroundColor="#f7768e"
SystemButtonsIconsColor="#f7768e"
SessionButtonTextColor="#f7768e"
VirtualKeyboardButtonTextColor="#f7768e"

DropdownTextColor="#1a1b26"
DropdownSelectedBackgroundColor="#bb9af7"
DropdownBackgroundColor="#f7768e"

HighlightTextColor="#7dcfff"
HighlightBackgroundColor="#bb9af7"
HighlightBorderColor="#bb9af7"

HoverUserIconColor="#bb9af7"
HoverPasswordIconColor="#bb9af7"
HoverSystemButtonsIconsColor="#bb9af7"
HoverSessionButtonTextColor="#bb9af7"
HoverVirtualKeyboardButtonTextColor="#bb9af7"

#################### Form ####################

PartialBlur="true"
FullBlur="false"
BlurMax="10"
Blur="0.5"

HaveFormBackground="true"
FormPosition="center"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="center"

#################### Interface Behavior ####################

HideVirtualKeyboard="true"
HideSystemButtons="true"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

#################### Translation ####################

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
